interface SEOProps {
    title?: string;
    description?: string;
    image?: string;
    url?: string;
    type?: 'website' | 'article' | 'product';
    // For articles
    publishedTime?: string;
    author?: string;
    // For products
    price?: number;
    availability?: 'InStock' | 'OutOfStock';
    // Schema data
    schemaData?: object;
}

const SITE_NAME = 'Moscow Mix';
const DEFAULT_DESCRIPTION = 'Moscow Mix creates solid 100% pure copper mugs and natural fire starters with authenticity and purity at their core. No plated copper, no fillers, no synthetic shortcuts.';
const DEFAULT_IMAGE = 'https://www.moscowmix.com/og-image.jpg';
const SITE_URL = 'https://www.moscowmix.com';

export default function SEO({
    title,
    description = DEFAULT_DESCRIPTION,
    image = DEFAULT_IMAGE,
    url = SITE_URL,
    type = 'website',
    publishedTime,
    author,
    price,
    availability = 'InStock',
    schemaData
}: SEOProps) {
    // Route metadata is generated by Next.js before the response is sent.
    // This component keeps structured data in the server-rendered HTML.
    if (!schemaData) return null;

    return (
        <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData).replace(/</g, '\\u003c') }}
        />
    );
}

// Pre-built schema generators
export function generateOrganizationSchema() {
    return {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "Moscow Mix",
        "url": "https://www.moscowmix.com",
        "logo": "https://www.moscowmix.com/apple-touch-icon.png",
        "description": DEFAULT_DESCRIPTION,
        "sameAs": [
            "https://www.instagram.com/moscowmix",
            "https://www.facebook.com/moscowmix"
        ]
    };
}

export function generateProductSchema(product: {
    name: string;
    description: string;
    image: string;
    price?: number;
    url: string;
    rating?: number;
    reviewCount?: number;
    amazonUrl?: string;
    availability?: 'InStock' | 'OutOfStock';
}) {
    return {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": product.name,
        "description": product.description,
        "image": product.image,
        "url": product.url,
        "brand": {
            "@type": "Brand",
            "name": "Moscow Mix"
        },
        ...(typeof product.price === 'number' && product.price > 0 && {
            "offers": {
                "@type": "Offer",
                "url": product.amazonUrl || product.url,
                "priceCurrency": "USD",
                "price": product.price.toFixed(2),
                "availability": `https://schema.org/${product.availability || 'InStock'}`,
                "itemCondition": "https://schema.org/NewCondition",
                "seller": {
                    "@type": "Organization",
                    "name": "Moscow Mix"
                }
            }
        }),
        ...(product.rating && product.reviewCount && product.reviewCount > 0 && {
            "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": product.rating,
                "reviewCount": product.reviewCount
            }
        })
    };
}

export function generateArticleSchema(article: {
    title: string;
    description: string;
    image: string;
    url: string;
    datePublished: string;
    dateModified?: string;
    author: string;
}) {
    return {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": article.title,
        "description": article.description,
        "image": article.image,
        "url": article.url,
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": article.url
        },
        "datePublished": article.datePublished,
        "dateModified": article.dateModified || article.datePublished,
        "author": {
            "@type": "Person",
            "name": article.author
        },
        "publisher": {
            "@type": "Organization",
            "name": "Moscow Mix",
            "logo": {
                "@type": "ImageObject",
                "url": "https://www.moscowmix.com/apple-touch-icon.png"
            }
        }
    };
}

export function generateBreadcrumbSchema(items: { name: string; url: string }[]) {
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": items.map((item, index, arr) => {
            const isLastItem = index === arr.length - 1;
            // Google requires valid absolute URLs for 'item' field
            // For the last item (current page), we omit the 'item' property entirely
            const listItem: Record<string, unknown> = {
                "@type": "ListItem",
                "position": index + 1,
                "name": item.name
            };
            // Only include 'item' for non-last items with valid URLs
            if (!isLastItem && item.url && item.url !== '#') {
                listItem["item"] = item.url;
            }
            return listItem;
        })
    };
}

export function generateFAQSchema(question: string, answer: string) {
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [{
            "@type": "Question",
            "name": question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": answer
            }
        }]
    };
}
